import type { AndroidResource } from "#/core/platforms/android/AndroidResource";
import { AndroidResourceType } from "#/core/platforms/android/AndroidResourceType";

const INDENT = "    ";

const XML_ESCAPES: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    "\"": "&quot;",
    "'": "&apos;",
};

/**
 * Renders Android resources as a `res/values` XML document.
 */
export class AndroidResourceRenderer {
    /**
     * Renders resources into one resource file.
     *
     * @param resources - Resources belonging to the file.
     * @param source - Token source name, rendered in the file header.
     * @returns XML document content.
     */
    render(resources: ReadonlyArray<AndroidResource>, source: string): string {
        const lines = [
            "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
            `<!-- Auto-generated by design-token-kit from ${this.#comment(source)}. DO NOT EDIT. -->`,
            "<resources>",
        ];
        let section: string | undefined;
        for (const resource of resources) {
            if (resource.section !== section) {
                section = resource.section;
                lines.push(...this.#renderSectionHeader(resource));
            }
            lines.push(...this.#renderResource(resource));
        }
        lines.push("", "</resources>", "");
        return lines.join("\n");
    }

    /**
     * Renders the header opening a section, carrying the token group path and
     * its description. Resources outside any group open no section.
     */
    #renderSectionHeader(resource: AndroidResource): string[] {
        if (!resource.section) return [];
        const title = this.#comment(resource.section);
        const description = resource.sectionDescription;
        if (!description) return ["", `${INDENT}<!-- ${title} -->`];

        return [
            "",
            `${INDENT}<!-- ${title}`,
            ...description.split("\n").map((line) => `${INDENT}     ${this.#comment(line)}`),
            `${INDENT}-->`,
        ];
    }

    #renderResource(resource: AndroidResource): string[] {
        const lines: string[] = [];
        if (resource.description) {
            lines.push(...this.#renderDescription(resource.description));
        }
        lines.push(this.#renderElement(resource));
        return lines;
    }

    /**
     * Renders one resource element. Android has no `<float>` element, so float
     * resources are declared as a typed `<item>`.
     */
    #renderElement(resource: AndroidResource): string {
        const value = this.#escape(resource.value);
        if (resource.type === AndroidResourceType.FLOAT) {
            return `${INDENT}<item name="${resource.name}" type="dimen" format="float">${value}</item>`;
        }
        return `${INDENT}<${resource.type} name="${resource.name}">${value}</${resource.type}>`;
    }

    #renderDescription(description: string): string[] {
        return description
            .split("\n")
            .map((line) => `${INDENT}<!-- ${this.#comment(line)} -->`);
    }

    #comment(text: string): string {
        return text.replace(/--+/g, "-").replace(/>$/, "").trim();
    }

    #escape(value: string): string {
        return value.replace(/[&<>"']/g, (char) => XML_ESCAPES[char]);
    }
}
