import { describe, it, expect } from "vitest";
import { DtcgJsonReader } from "#/core/io/DtcgJsonReader";
import { DtcgList } from "#/core/model/DtcgList";
import {
    DtcgTokenSwiftUiConverter,
    type DtcgTokenSwiftUiConverterOptions,
} from "#/core/platforms/swiftui/DtcgTokenSwiftUiConverter";

function convert(json: object): string {
    const doc = new DtcgJsonReader().parse(JSON.stringify(json));
    return new DtcgTokenSwiftUiConverter().convertDocument(doc);
}

function convertList(
    base: object,
    themes: Record<string, object> = {},
    options?: DtcgTokenSwiftUiConverterOptions,
): string {
    const reader = new DtcgJsonReader();
    const baseDoc = reader.parse(JSON.stringify(base));
    const themeMap = new Map(
        Object.entries(themes).map(([name, doc]) => [name, reader.parse(JSON.stringify(doc))]),
    );
    return new DtcgTokenSwiftUiConverter(options).convertList(new DtcgList(baseDoc, themeMap));
}

describe("DtcgTokenSwiftUiConverter scalars", () => {
    it("wraps output in a DesignTokens enum with SwiftUI import", () => {
        const out = convert({
            color: {
                base: {
                    red: {
                        $type: "color",
                        $value: { colorSpace: "srgb", components: [1, 0.2, 0.2] },
                    },
                },
            },
        });
        expect(out).toContain("import SwiftUI");
        expect(out).toContain("enum DesignTokens {");
    });

    it("emits nested enums for groups and static let for tokens", () => {
        const out = convert({
            spacing: { md: { $type: "dimension", $value: { value: 16, unit: "px" } } },
        });
        expect(out).toContain("enum Spacing {");
        expect(out).toContain("static let md: CGFloat = 16");
    });

    it("preserves references as Swift constant paths", () => {
        const out = convert({
            color: {
                base: {
                    red: {
                        $type: "color",
                        $value: { colorSpace: "srgb", components: [1, 0.2, 0.2] },
                    },
                },
                semantic: { primary: { $type: "color", $value: "{color.base.red}" } },
            },
        });
        expect(out).toContain("static let primary = DesignTokens.Color.Base.red");
    });

    it("escapes Swift reserved words in identifiers", () => {
        const out = convert({
            color: {
                default: {
                    $type: "color",
                    $value: { colorSpace: "srgb", components: [0, 0, 0] },
                },
            },
        });
        expect(out).toContain("static let default_ =");
    });

    it("emits /// doc comment from a token $description", () => {
        const out = convert({
            color: {
                $description: "Full color palette.",
                white: {
                    $type: "color",
                    $description: "Pure white for backgrounds.",
                    $value: { colorSpace: "srgb", components: [1, 1, 1] },
                },
            },
        });
        expect(out).toContain("/// Full color palette.");
        expect(out).toContain("/// Pure white for backgrounds.");
    });

    it("emits /// doc comment from a group $description", () => {
        const out = convert({
            primitive: {
                $description: "Raw design values.",
                color: {
                    $type: "color",
                    $value: { colorSpace: "srgb", components: [1, 1, 1] },
                },
            },
        });
        expect(out).toContain("/// Raw design values.");
    });

    it("handles multi-line descriptions", () => {
        const out = convert({
            color: {
                $description: "Full color palette.\nIncludes brand, status, and neutral colors.",
                white: {
                    $type: "color",
                    $value: { colorSpace: "srgb", components: [1, 1, 1] },
                },
            },
        });
        expect(out).toContain("/// Full color palette.\n    /// Includes brand, status, and neutral colors.");
    });

    it("does not emit /// when description is absent", () => {
        const out = convert({
            color: {
                white: {
                    $type: "color",
                    $value: { colorSpace: "srgb", components: [1, 1, 1] },
                },
            },
        });
        expect(out).not.toContain("///");
    });

    it("emits auto-generated file header", () => {
        const out = convert({});
        expect(out).toMatch(/^\/\/ Auto-generated by design-token-kit\. DO NOT EDIT\.\n/);
    });

    it("returns an empty DesignTokens enum for empty input", () => {
        const out = convert({});
        expect(out).toContain("enum DesignTokens {");
        expect(out).not.toContain("static let");
    });
});

describe("DtcgTokenSwiftUiConverter composites", () => {
    it("emits a ShadowToken struct and value when a shadow token exists", () => {
        const out = convert({
            elevation: {
                low: {
                    $type: "shadow",
                    $value: {
                        color: { colorSpace: "srgb", components: [0, 0, 0], alpha: 0.2 },
                        offsetX: { value: 0, unit: "px" },
                        offsetY: { value: 2, unit: "px" },
                        blur: { value: 4, unit: "px" },
                        spread: { value: 0, unit: "px" },
                    },
                },
            },
        });
        expect(out).toContain("struct ShadowToken {");
        expect(out).toContain("static let low: [ShadowToken] = [ShadowToken(");
    });

    it("renders a multi-layer shadow as an array of ShadowToken", () => {
        const out = convert({
            elevation: {
                high: {
                    $type: "shadow",
                    $value: [
                        { color: { colorSpace: "srgb", components: [0, 0, 0], alpha: 0.2 }, offsetX: { value: 0, unit: "px" }, offsetY: { value: 1, unit: "px" }, blur: { value: 2, unit: "px" }, spread: { value: 0, unit: "px" } },
                        { color: { colorSpace: "srgb", components: [0, 0, 0], alpha: 0.1 }, offsetX: { value: 0, unit: "px" }, offsetY: { value: 4, unit: "px" }, blur: { value: 8, unit: "px" }, spread: { value: 0, unit: "px" } },
                    ],
                },
            },
        });
        expect(out).toContain("static let high: [ShadowToken] = [");
        expect(out.match(/ShadowToken\(/g)?.length).toBe(2);
    });

    it("renders a strokeStyle object with dashed derived from dashArray", () => {
        const out = convert({
            stroke: {
                dashed: {
                    $type: "strokeStyle",
                    $value: { dashArray: [{ value: 2, unit: "px" }, { value: 2, unit: "px" }], lineCap: "butt" },
                },
            },
        });
        expect(out).toContain("StrokeStyleToken(dashed: true)");
    });

    it("does not emit composite structs when no composite tokens exist", () => {
        const out = convert({
            spacing: { md: { $type: "dimension", $value: { value: 16, unit: "px" } } },
        });
        expect(out).not.toContain("struct ShadowToken");
        expect(out).not.toContain("struct TypographyToken");
    });

    it("emits a TypographyToken struct and value", () => {
        const out = convert({
            text: {
                body: {
                    $type: "typography",
                    $value: {
                        fontFamily: ["Inter"],
                        fontSize: { value: 16, unit: "px" },
                        fontWeight: 400,
                        letterSpacing: { value: 0, unit: "px" },
                        lineHeight: 1.5,
                    },
                },
            },
        });
        expect(out).toContain("struct TypographyToken {");
        expect(out).toContain("static let body = TypographyToken(");
    });

    it("qualifies SwiftUI types so a group named 'color' does not shadow SwiftUI.Color", () => {
        const out = convert({
            color: {
                brand: {
                    $type: "color",
                    $value: { colorSpace: "srgb", components: [1, 0, 0] },
                },
            },
        });
        expect(out).toContain("enum Color {");
        expect(out).toContain("SwiftUI.Color(");
        expect(out).not.toMatch(/= Color\(/);
    });

    it("routes a strokeStyle keyword through StrokeStyleToken", () => {
        const dashed = convert({
            stroke: { a: { $type: "strokeStyle", $value: "dashed" } },
        });
        expect(dashed).toContain("StrokeStyleToken(dashed: true)");

        const solid = convert({
            stroke: { b: { $type: "strokeStyle", $value: "solid" } },
        });
        expect(solid).toContain("StrokeStyleToken(dashed: false)");
    });

    it("preserves a strokeStyle reference instead of flattening it", () => {
        const out = convert({
            stroke: {
                base: { $type: "strokeStyle", $value: "dashed" },
                alias: { $type: "strokeStyle", $value: "{stroke.base}" },
            },
        });
        expect(out).toContain("static let alias = DesignTokens.Stroke.base");
        expect(out).not.toContain("static let alias = StrokeStyleToken(dashed");
    });

    it("uses SwiftUI.Font.custom when typography has a concrete fontFamily", () => {
        const out = convert({
            text: {
                heading: {
                    $type: "typography",
                    $value: {
                        fontFamily: ["Inter"],
                        fontSize: { value: 24, unit: "px" },
                        fontWeight: 700,
                        letterSpacing: { value: 0, unit: "px" },
                        lineHeight: 1.2,
                    },
                },
            },
        });
        expect(out).toContain("SwiftUI.Font.custom(");
    });

    it("emits a standalone fontFamily list token as a [String] literal", () => {
        const out = convert({
            font: {
                family: {
                    body: { $type: "fontFamily", $value: ["Inter", "Arial", "sans-serif"] },
                },
            },
        });
        expect(out).toContain(`["Inter", "Arial", "sans-serif"]`);
        expect(out).toMatch(/static let body/);
    });

    it("preserves a reference to a fontFamily list token", () => {
        const out = convert({
            font: {
                family: {
                    body: { $type: "fontFamily", $value: ["Inter", "Arial", "sans-serif"] },
                },
            },
            text: {
                "family-body": { $type: "fontFamily", $value: "{font.family.body}" },
            },
        });
        expect(out).toContain("static let familyBody = DesignTokens.Font.Family.body");
    });
});

const THEMED_BASE = {
    primitive: {
        color: {
            background: { $type: "color", $value: { colorSpace: "srgb", components: [1, 1, 1] } },
            text: { $type: "color", $value: { colorSpace: "srgb", components: [0, 0, 0] } },
        },
    },
    semantic: {
        color: {
            surface: { $type: "color", $value: "{primitive.color.background}" },
        },
    },
};

const DARK_OVERRIDE = {
    primitive: {
        color: {
            background: { $type: "color", $value: { colorSpace: "srgb", components: [0.1, 0.1, 0.1] } },
        },
    },
};

describe("DtcgTokenSwiftUiConverter enum themes", () => {
    it("emits a base enum and a full per-theme enum", () => {
        const out = convertList(THEMED_BASE, { dark: DARK_OVERRIDE });
        expect(out).toContain("enum DesignTokens {");
        expect(out).toContain("enum DesignTokensDark {");
        expect((out.match(/import SwiftUI/g) ?? []).length).toBe(1);
    });

    it("renders an overridden token as a value in the theme enum", () => {
        const out = convertList(THEMED_BASE, { dark: DARK_OVERRIDE });
        expect(out).toContain("SwiftUI.Color(.sRGB, red: 0.1, green: 0.1, blue: 0.1");
    });

    it("renders a non-overridden token as a reference to the base enum", () => {
        const out = convertList(THEMED_BASE, { dark: DARK_OVERRIDE });
        expect(out).toContain("static let text = DesignTokens.Primitive.Color.text");
    });

    it("roots an intra-theme reference at the theme's own namespace", () => {
        const out = convertList(THEMED_BASE, { dark: DARK_OVERRIDE });
        expect(out).toContain("static let surface = DesignTokensDark.Primitive.Color.background");
    });

    it("keeps base semantic references rooted at the base enum", () => {
        const out = convertList(THEMED_BASE, { dark: DARK_OVERRIDE });
        expect(out).toContain("static let surface = DesignTokens.Primitive.Color.background");
    });

    it("pascalizes a multi-word theme name in the enum name", () => {
        const out = convertList(THEMED_BASE, { "high-contrast": DARK_OVERRIDE });
        expect(out).toContain("enum DesignTokensHighContrast {");
        expect(out).toContain("static let surface = DesignTokensHighContrast.Primitive.Color.background");
    });

    it("produces unchanged single-doc output when there are no themes", () => {
        const viaList = convertList(THEMED_BASE);
        const viaDoc = convert(THEMED_BASE);
        expect(viaList).toBe(viaDoc);
        expect(viaList).not.toContain("DesignTokensDark");
        expect(viaList).not.toContain("struct Theme");
    });
});

describe("DtcgTokenSwiftUiConverter struct themes", () => {
    it("emits a Theme struct mirroring the token tree", () => {
        const out = convertList(THEMED_BASE, { dark: DARK_OVERRIDE }, { swiftType: "struct" });
        expect(out).toContain("struct Theme {");
        expect(out).toContain("let surface: SwiftUI.Color");
    });

    it("emits the enum layer alongside the struct layer", () => {
        const out = convertList(THEMED_BASE, { dark: DARK_OVERRIDE }, { swiftType: "struct" });
        expect(out).toContain("enum DesignTokens {");
        expect(out).toContain("enum DesignTokensDark {");
    });

    it("emits a base instance referencing the base enum", () => {
        const out = convertList(THEMED_BASE, { dark: DARK_OVERRIDE }, { swiftType: "struct" });
        expect(out).toContain("static let base = Theme(");
        expect(out).toContain("DesignTokens.Semantic.Color.surface");
    });

    it("emits a theme instance referencing the theme enum", () => {
        const out = convertList(THEMED_BASE, { dark: DARK_OVERRIDE }, { swiftType: "struct" });
        expect(out).toContain("static let dark = Theme(");
        expect(out).toContain("DesignTokensDark.Semantic.Color.surface");
    });

    it("holds enum references in struct fields, not color literals", () => {
        const out = convertList(THEMED_BASE, { dark: DARK_OVERRIDE }, { swiftType: "struct" });
        const extension = out.slice(out.indexOf("extension Theme"));
        expect(extension).not.toContain("SwiftUI.Color(");
    });

    it("emits a single default instance in the degenerate no-themes struct", () => {
        const out = convertList(THEMED_BASE, {}, { swiftType: "struct" });
        expect(out).toContain("struct Theme {");
        expect(out).toContain("static let light = Theme(");
        expect(out).toContain("DesignTokens.Semantic.Color.surface");
        expect(out).not.toContain("DesignTokensDark");
    });
});
